CREATE OR REPLACE PROCEDURE P_LOAD_DATA IS
BEGIN
-- zip
MERGE
INTO ZIP Z
USING
(
    SELECT DISTINCT ZIP, STATE
    FROM CUSTOMERS
) SUB
ON (Z.CODE = SUB.ZIP)
WHEN NOT MATCHED THEN 
    INSERT(CODE, STATE) VALUES(SUB.ZIP, SUB.STATE);
    
-- time
MERGE
INTO TIME T
USING
(
    SELECT DISTINCT EXTRACT(MONTH FROM ORDERDATE) MONTH, EXTRACT(YEAR FROM ORDERDATE) YEAR
    FROM ORDERS
) SUB2
ON (T.MONTH = SUB2.MONTH AND T.YEAR = SUB2.YEAR)
WHEN NOT MATCHED THEN
    INSERT(MONTH, YEAR) VALUES(SUB2.MONTH, SUB2.YEAR);
    
-- sale
MERGE
INTO SALE S
USING 
(
    SELECT
        (SELECT ID FROM ZIP WHERE CODE = C.ZIP) ZIP_ID,
        (SELECT ID FROM TIME WHERE MONTH = EXTRACT(MONTH FROM O.ORDERDATE) AND YEAR = EXTRACT(YEAR FROM O.ORDERDATE)) TIME_ID,
        SUM(B.RETAIL * OI.QUANTITY) SALE_AMOUNT
    FROM BOOKS B
        JOIN ORDERITEMS OI ON B.ISBN = OI.ISBN
        JOIN ORDERS O ON OI.ORDER# = O.ORDER#
        JOIN CUSTOMERS C ON O.CUSTOMER# = C.CUSTOMER#
        GROUP BY C.ZIP, EXTRACT(MONTH FROM O.ORDERDATE), EXTRACT(YEAR FROM O.ORDERDATE)
) SUB3
ON (S.ZIP_ID = SUB3.ZIP_ID AND S.TIME_ID = SUB3.TIME_ID)
WHEN NOT MATCHED THEN
    INSERT(ZIP_ID, TIME_ID, SALE) VALUES(SUB3.ZIP_ID, SUB3.TIME_ID, SUB3.SALE_AMOUNT)
WHEN MATCHED THEN
    UPDATE SET S.SALE = SUB3.SALE_AMOUNT; 
END;