DROP SEQUENCE IF EXISTS SEQ_INCR_ZIP_ID

CREATE SEQUENCE SEQ_INCR_ZIP_ID
INCREMENT BY 1
START WITH 1;

CREATE OR REPLACE TRIGGER T_SET_ZIP_ID
BEFORE INSERT ON ZIP
FOR EACH ROW
DECLARE
BEGIN
    IF(:NEW.id IS NULL)
    THEN
        :NEW.ID := SEQ_INCR_ZIP_ID.NEXTVAL;
    END IF;
END;

INSERT INTO ZIP (code, state) VALUES ('12345', 'XD');

SELECT *
FROM ZIP;